# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Add these at the top level (not under marketing)
description: "Tuna Abay, Economics PhD candidate at European University Institute. Research in Economic growth, innovation, technological change and firm dynamics."
author: "Tuna Abay"
keywords: ["Tuna Abay", "Economics", "PhD", "European University Institute", "Research", "Academic", "Job Market", "Job Market Candidate", "Economic Growth", "Innovation", "Technological Change", "Firm Dynamics"]


custom_css: ["assets/css/custom.css"]

appearance:
  mode: system
  color: zinc    # closest to ocean blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'European University Institute'
    description: 'Tuna Abay, Economics PhD candidate at European University Institute. Academic research, publications, and working papers in economics.'
    twitter: ''  # Add your Twitter handle if you have one, or leave blank
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ''  # We'll add this after setting up Google Search Console
    baidu: ''


# Site header
header:
  navbar:
    background-color: red
    enable: true
    blox: "navbar"
    # Align menu links: `left`, `center`, or `right`
    align: "right"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Tuna Abay"

# Site footer
footer:
  copyright:
    notice: '© {year} Tuna Abay. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

icon:
  pack: "fas"
  name: "user-graduate"  # or just use the default favicon files